#
# This global values.yaml file contains Helm values that apply to an entire environment.
#
global:
#
# Global values directory path used in ArgoCD applications. Typically could not change unless
# you  decide to change the Git Submodule  directories
#
  values_location: /values/global/values.yaml
#
# Domain for Telco/Enterprise environment assigned to OCP
# Each cluster deployed will be a subdomain of this domain 
#
  domain: tmetse.lab
#
# Site wide DNS server configured on target clusters.
# Note that MGMT clusters have it set as part of the day0 install
#
  dns: 192.168.52.120
#
# Site wide NTP server used temporarily during the Assisted-Installer install else only unreachable public NTP
# servers will be configured by AI. It will get overwritten permanently by chrony_conf below via a new MC.
#
  ntp: time.google.com
#
# Container image mirror registry access information for OCP.
#
#  registry:
#    url: "lab-registry.mgmt.tmetse.lab"
#    path: ocp41046
#    user: "gitops_mgmt"
#    password: "Redhat01"
#
# Prefix for target cluster repo naming
#
  cluster_git_prefix: "cluster"
#
# Site mirror information required by Hive and Assisted-Installer
#
  mirror:
    # NOT USED at the moment. DO NOT CHANGE
    # Operator CatalogSource to use, i.e. select the mirror or Direct to Red Hat
    # Red Hat Direct is "redhat-operators"
    # Local mirror is "redhat-operator-index"
    operator_source: redhat-operator-index
    #
    # OCP install version defined in the AgentClusterInstall CRD for each target cluster
    # Must match anm entry in the list below defined in Hive ClusterImageSet CRDs
    #
    #install_mirror_name: "openshift-v4.10.12"
    install_mirror_name: "openshift-v4.10.46-disconnected"
    #
    # List of OCP version mirror URLs available to install. At least oen must be defined.
    # 
    # export OCP_REL_MAJ=4
    # export OCP_REL_MIN=10
    # export OCP_REL_MNT=45
    # export LOCAL_REGISTRY='lab-registry.mgmt.tmetse.lab'
    # export LOCAL_REGISTRY_ORG=cache-quayio
    # export RELEASE_PATH=$(curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OCP_REL_MAJ}.${OCP_REL_MIN}.${OCP_REL_MNT}/release.txt | grep 'Pull From: quay.io' | awk -F ' ' '{print $3}' | awk -F 'quay.io/' '{print $2}')
    # export LOCAL_PATH=$LOCAL_REGISTRY/$LOCAL_REGISTRY_ORG'/'$RELEASE_PATH
    # echo $LOCAL_PATH
    # 
    list:
      - name: openshift-v4.10.46-manage-mirror
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift-release-dev/ocp-release:4.10.46-x86_64-ocp-release
      - name: openshift-v4.10.47-manage-mirror
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift-release-dev/ocp-release:4.10.47-x86_64-ocp-release
      - name: openshift-v4.10.48-manage-mirror
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift-release-dev/ocp-release:4.10.48-x86_64-ocp-release
      - name: openshift-v4.10.51-manage-mirror
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift-release-dev/ocp-release:4.10.51-x86_64-ocp-release
      - name: openshift-v4.10.52-manage-mirror
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift-release-dev/ocp-release:4.10.52-x86_64-ocp-release
      - name: openshift-v4.10.46-disconnected
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift4-release-images:4.10.46-x86_64
      - name: openshift-v4.10.47-disconnected
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift4-release-images:4.10.47-x86_64
      - name: openshift-v4.10.48-disconnected
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift4-release-images:4.10.48-x86_64
      - name: openshift-v4.10.51-disconnected
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift4-release-images:4.10.51-x86_64
      - name: openshift-v4.10.52-disconnected
        path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift4-release-images:4.10.52-x86_64

        #FAILS path: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift-release-dev/ocp-release:4.10.46-x86_64

        #path: quay.io/openshift-release-dev/ocp-release@sha256:5f9ac79c9c257c28b8b51e79a0382de285d6e4c4e4537710b7c117601d320293
       
        #path: lab-registry.mgmt.tmetse.lab/cache-quayio/openshift-release-dev/ocp-release@sha256:5f9ac79c9c257c28b8b51e79a0382de285d6e4c4e4537710b7c117601d320293
  # 
  # Quay specific configurations. Not needed if another vendor image registry is used.
  # 
  quay:
  #
  # The secret the config will be saved in
  #
    registry_name: ""
    config_secret: ""
    #
    # config_yaml is set to the Quay configuration customising items like a user friendly server name.
    # This config also configures an external S3 storage to be used for image storage.
    #
    # ssl_cert and ssl_key are required to configure a site wide self-signed TLS certificates for the server.
    #
    config_yaml: ""
    ssl_cert: ""
    ssl_key: ""
#
# Assisted Installer (standalone, infrastructure operator) site wide configurations
#
  ai:
    #
    # SSH public key for accessing deployed nodes
    #
      ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgexmgIbvhy8H4I2xx0GRFId3VZgBTwRuCjufMcwxIg77t9LkC4WAV5vSqYdrxkyHPr1fyxvm1RDVmsOudndXKMrCAIF53M8izcFPDcOwmr037Z8/2HPJfB7JgnuN85W/0zUNuYwUVeKfpiLg3FOaTf4piU7Ql4X2Zlyi3cemmr0n0ctSLQlNB3bb8FyCyc+t5l3DrdhuNG43xBOada6ZHT+Kw3ybKANziVemEFYEL/7N8ovq5f1P0rKZvpl5IpR8SvSnBwLGEkhBu2x/rHBCm5ahxgvTbqeExfFKSiW0YJkIkpbm7bUstSvIOQ6Bni65wxxERwas3JKmakQSRVHJkcVzLhPNUA3PYgcobyiJJ0+BiPywtGoXwKBoT+B4q7V1lb8+U5phmS7+G1T/9+ZsvFpnrxkDV9in//r1ibuaOzvvbJA/ZHQGk4norrwIUafWYx07tBQ5jUFgUfJ1J1zolpyIoGVge4K1xa01kd/LO2p3rrIGhGHpObNF8O5eDEzM= tmeadmin@kvm01.tmetse.lab'
    # 
    # Site CA authority certificate
    #
      ca: |-
        -----BEGIN CERTIFICATE-----
        MIIEiDCCAvCgAwIBAgIBATANBgkqhkiG9w0BAQsFADA1MRMwEQYDVQQKDApUTUVU
        U0UuTEFCMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjIxMDE4
        MTIzOTMzWhcNNDIxMDE4MTIzOTMzWjA1MRMwEQYDVQQKDApUTUVUU0UuTEFCMR4w
        HAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggGiMA0GCSqGSIb3DQEBAQUA
        A4IBjwAwggGKAoIBgQC2rRfJXR+DFbh/h2ohS8fgDwpqrV6iLBcWTlosl7GgXz5J
        K3gnbUMRde2ocZ/qdCA5MrGNfwq6t3s55MJOb4S9JkdAOe6e4Gn6sRZssd8o10rb
        r/fsOFvuKVtBTfdQupj/3ahCPNgj8fv/rOw6UphKOaGx6vSZMxwck2aAWMLI8Q/R
        MGmVzbwsy2oD3AXQuWdYbRB1Xm7KirqnmgH8EHpmL8lubgWE0McD7+Nh4zN5YThD
        doV68FjPNuQHlQSeGNyY1XkJdVmI+hS2DZQ8V7/SJOqzbNEYtKfrvq90rrOP7cQr
        TpbuyU/HIq0JzxbOnvebxVNpULwL7PuyhAHEH1iiADHxTgzrelJVwvzsdcPy2d/H
        A28a2eKh9yE6O+q/uG0nArzHpB3JOJfHsC/uZ8dK3/uGHql9iooH9Exptou1p9H9
        APifQ/k9VMJvEYlbl7rRPFLlIzWKothDZXCC+ehvKfVJOMSOwcra3iWakRn77yXs
        jdi9pcENWL9dwUYpiosCAwEAAaOBojCBnzAfBgNVHSMEGDAWgBRhuy2vYNtM+fvm
        Z53mZfNQpKSCADAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBxjAdBgNV
        HQ4EFgQUYbstr2DbTPn75med5mXzUKSkggAwPAYIKwYBBQUHAQEEMDAuMCwGCCsG
        AQUFBzABhiBodHRwOi8vaXBhLWNhLnRtZXRzZS5sYWIvY2Evb2NzcDANBgkqhkiG
        9w0BAQsFAAOCAYEAHs7zP2n5kgC2AkGQOOSy+DUco4zTa3/udAGllXESPHdb69rp
        Bd4qgwy95ORwYaaTCBKpom5aDPZ0BoA95Fc4ISU3t2QtgnqsDumpsELtTfgcc4uK
        9NsKYbaXTe2XnqTcrhaWTneJdA5Wo8BxX8QrhjhdedN8rFQI4aZw5YuDNogFwmxM
        eucfoSuhwAkfgRnoohPAp6A5FdtvzlyQbNyJURCo3Cpnu3Fh0KYMtTLjeXkLgDf4
        xDmQmAZb7KnmCGwllJ34nCvE67YRq6Coz4clDRTGpbTVixFKjehEI3fUeaxsg7uJ
        7zPM35n4kWRD4gFWZkwIh4d3gPeDZyc7xlJ4pNNBVY2QB+uT7s2xqLRK3exmghpY
        L+JKUSbvHnJw4g0pOguWOaPD5Zj2mkKF5L3M7yaAIyhUhMbtA3TMDg+ZlwGA5Zz9
        IOSaAzTsyekPmalBU/MODjk/fEXjtSOlGfiBLMgXi1Qjk0cQolC+DwAeP6w3urXl
        2R0jyNgCJkq1/RnA
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIEzTCCAzWgAwIBAgIBDjANBgkqhkiG9w0BAQsFADA1MRMwEQYDVQQKDApUTUVU
        U0UuTEFCMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjMwMzAy
        MDUzMTAxWhcNMjUwMzAyMDUzMTAxWjA3MRMwEQYDVQQKDApUTUVUU0UuTEFCMSAw
        HgYDVQQDDBdpbmdyZXNzLm1nbXQudG1ldHNlLmxhYjCCASIwDQYJKoZIhvcNAQEB
        BQADggEPADCCAQoCggEBAKyRR6+BX1JDh02AouGRAdaEvLQiFIMPaZVXkCmBrWmu
        uEeSLh2NsQ9BuqHWhrTEEizX3ZS4X8UsxGfhUGFZcQUKNeJgrnFFmGZuXsEU1dOQ
        AuA5XyoUKbLtliyZ7JgfWg9OeBSBfFF0m40xYN3znQoyAxBrcurikLKQYZYfQTmN
        1P0Qkoq/SSWSEry/ptprG+Vdn8dgPgfRMKnfjV16+fzZWvWk4BpKDpoUk0cfVF3S
        a4ayvWbLa58UI5ZtLVwVdLJqQLIKTX2ljsH5BhqCYO8e9uTd5av3E45t3ZEi7TZd
        kvEEmbBG0r/fkPPEb8D2ySlzzWwWHGMnjwszCGgdVQkCAwEAAaOCAWQwggFgMB8G
        A1UdIwQYMBaAFGG7La9g20z5++ZnneZl81CkpIIAMDwGCCsGAQUFBwEBBDAwLjAs
        BggrBgEFBQcwAYYgaHR0cDovL2lwYS1jYS50bWV0c2UubGFiL2NhL29jc3AwDgYD
        VR0PAQH/BAQDAgTwMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjB1BgNV
        HR8EbjBsMGqgMqAwhi5odHRwOi8vaXBhLWNhLnRtZXRzZS5sYWIvaXBhL2NybC9N
        YXN0ZXJDUkwuYmluojSkMjAwMQ4wDAYDVQQKDAVpcGFjYTEeMBwGA1UEAwwVQ2Vy
        dGlmaWNhdGUgQXV0aG9yaXR5MB0GA1UdDgQWBBRC73+ilkq+t4wtUcL5geTedYwa
        czA6BgNVHREEMzAxghYqLmFwcHMubWdtdC50bWV0c2UubGFighdpbmdyZXNzLm1n
        bXQudG1ldHNlLmxhYjANBgkqhkiG9w0BAQsFAAOCAYEAga/kREtJ9zMWIF763umR
        lMf/aAitVAeN3qWJ2TJGjsAb0qpYCSz+WaQQRs8exokxhZyooAaob6n28uavfm7W
        xplDLB3Ow9kENaTTg5Q64/VTrX6UCzW//RBGvCTXLq070WOF99CGGTvJX8U7/ggu
        Y4Zb1g3IGmRTNFMJ+Tn6a6ej3tkN3/d+J4cgJH8qES56v1IRcveNq7QXynbS0upm
        ZcIX7XT9j0dGFsmi4wbRPInkwrEvrjbUrBliUZti7xytHDKKzOOy6LlyVgf9ZnFb
        9CDsFlRTMnAZs8KE78AQi8b/orcu42t8ow4bdnmQ5tMwnGLnDs7DjPEEAUliG88h
        itnc01vDLxTRIcuZPxGBCQshKe4zrAMamt5nmSmghTLndSVNLy4zIzExV1TSnnFi
        8pEvhr9bsOOMoLkd/jG2jjsiIP9DeF0yn6HURCCRIdI5Y88jCLoHKnU42HhROW+j
        YTthPECCRz/mteTnvxgnbKVGI+KyG73XQr5tpIh6BzMu
        -----END CERTIFICATE-----

    #
    # Pull_Secret OCP secret name  and local registry pull_secret for target clusters.
    # Global pull secret to merge with the local_registry is dynamically taken from Hub Cluster
    #
      pull_secret_name: multiclusterhub-operator-pull-secret
#
# Site wide Openshift GitOps configuration options
#
  gitops:
    namespace: telco-gitops
    common_label: "telco-gitops/automation: combined-ran"
    service_account: cli-job-sa
    service_account_name: cli-job-sa
    hook_image: registry.redhat.io/openshift4/ose-tools-rhel8:latest
    #hook_image: registry.redhat.io/openshift4/ose-tools-rhel8@sha256:3a430c4571983d4e774a7c2a6575086ad758d6a76724cc264ba80766abf5ee6b
    #hook_image: lab-registry.mgmt.tmetse.lab/gitops_mgmt/ose-tools-rhel8@sha256:c2230682e3f3a492967e7b62171cf363cff24fcb8252b2a0ca50e26dbbeb1b24
  chrony_conf: |-
    # Chrony config optimized for control plane
    driftfile /var/lib/chrony/drift
    # By default, chronyd accelerates or slows the system clock to fix any time drift.
    # If the drift is too big, chrony fails to fix the drift. To overcome this,
    # update chrony.conf to force a time sync if the drift exceeds the threshold specified.
    makestep 1.0 -1
    rtcsync
    logdir /var/log/chrony
    # NTP Servers
    #keyfile /etc/chrony.keys
    #server ntp.example.com iburst
    #pool 192.168.254.10 iburst
    pool 2.rhel.pool.ntp.org iburst
    pool 2.fedora.pool.ntp.org iburst