mgmt:
  #
  # name of management cluster. FQDN will be the <name.<global.domain>
  name: mgmt
  #  
  # Git URL for this management cluster
  git_url: https://github.com/tme-tse-lab/mgmt-mgmt.tmetse.lab.git
  #
  # OPTIONAL
  # Set to override the global credentials for the given management cluster and all its target clusters
  #
  #git_user: ""
  #git_token: ""
  #
  # This management clusters values directory path used in ArgoCD applications. Typically would not change unless
  # you  decide to change the Git Submodule  directories
  values_location: /values/mgmt.tmetse.lab/values.yaml
  #
  # Container image mirror registry access information for OCP.
  #
  registry:
    url: "lab-registry.mgmt.tmetse.lab"
    path: ocp41038
    user: "gitops_mgmt"
    password: "Redhat01"
    caching: false
  #  
  # Defines if ODF/OCS will be using internal rook/ceph  or external
  # Uncomment the desired setting
  #default_storage_class: "odf-lvm-vg1"
  default_storage_class: "ocs-external-storagecluster-ceph-rbd"
  #default_storage_class: "ocs	-storagecluster-ceph-rbd"
  #
  # External Ceph
  # -------------  
  # Need ceph-external-cluster-details-exporter.py from your stable ODF operator to genrate the external_cluster_details
  #
  # Example:
  # ceph osd pool create mgmt-rbd 128
  # ceph osd pool create mgmt-fs-data 64
  # ceph osd pool create mgmt-fs-metadata 64
  # ceph fs new mgmt-fs mgmt-fs-metadata mgmt-fs-data
  #
  # python3 ceph-external-cluster-details-exporter.py \
  #   --run-as-user client.mgmt.health \
  #   --monitoring-endpoint 192.19.130.11 \
  #   --rgw-endpoint  192.19.130.11:80 \
  #   --rbd-data-pool-name mgmt-replicapool \
  #   --rados-namespace mgmt-radosNamespace \
  #   --cluster-name mgmt-rookStorage \
  #   --cephfs-filesystem-name mgmt-fs \
  #   --cephfs-metadata-pool-name mgmt-fs-metadata \
  #   --cephfs-data-pool-name mgmt-fs-data \
  #   --rbd-data-pool-name mgmt-rbd
  #  
  external_cluster_details: '[{"name": "rook-ceph-mon-endpoints", "kind": "ConfigMap", "data": {"data": "192.168.52.57=192.168.52.57:6789", "maxMonId": "0", "mapping": "{}"}}, {"name": "rook-ceph-mon", "kind": "Secret", "data": {"admin-secret": "admin-secret", "fsid": "0f773420-5a7c-11ed-920d-b49691bbdb9e", "mon-secret": "mon-secret"}}, {"name": "rook-ceph-operator-creds", "kind": "Secret", "data": {"userID": "client.mgmt.health", "userKey": "AQCbNGpjLV5eMhAAQj+RHbvK24su0cT05ITiwQ=="}}, {"name": "monitoring-endpoint", "kind": "CephCluster", "data": {"MonitoringEndpoint": "192.168.52.57", "MonitoringPort": "9283"}}, {"name": "ceph-rbd", "kind": "StorageClass", "data": {"pool": "ocp-mgmt-rbd"}}, {"name": "rook-csi-rbd-node", "kind": "Secret", "data": {"userID": "csi-rbd-node", "userKey": "AQAiMGpj6iamGRAAbrvBqLDzOZUXb/CccrGFxA=="}}, {"name": "rook-csi-rbd-provisioner", "kind": "Secret", "data": {"userID": "csi-rbd-provisioner", "userKey": "AQAiMGpjccvRGRAAewF25CzCRi3utsvAeBksUQ=="}}, {"name": "rook-csi-cephfs-provisioner", "kind": "Secret", "data": {"adminID": "csi-cephfs-provisioner", "adminKey": "AQCbNGpjIjrQMhAAPlagEa+hdrFut4PvJFXaCg=="}}, {"name": "rook-csi-cephfs-node", "kind": "Secret", "data": {"adminID": "csi-cephfs-node", "adminKey": "AQCbNGpjfbWhMhAAyg+P++JN5AGoksvvwmIr5Q=="}}, {"name": "rook-ceph-dashboard-link", "kind": "Secret", "data": {"userID": "ceph-dashboard-link", "userKey": "https://192.168.52.57:8443/"}}, {"name": "cephfs", "kind": "StorageClass", "data": {"fsName": "ocp-mgmt-fs", "pool": "ocp-mgmt-fs-data"}}]'
  #
  # For multinode Management set to 3 and SNO set to 1
  ingress_replica: 3
  #
  # Define the master nodes and storage requirements
  # Assumed this day0 cluster is deployed by IPI baremetal or Assisted-Installer as the BMH operator is required
  nodes:
    masters:
    - name: "master1.mgmt.tmetse.lab"
      lso: "true"
      odf: "true"
    - name: "master2.mgmt.tmetse.lab"
      lso: "true"
      odf: "true"
    - name: "master3.mgmt.tmetse.lab"
      lso: "true"
      odf: "true"
  # 
  # ACM Related
  acm:
    thanos_yaml: |-
      type: s3
      config:
        bucket: "ocp-mgmt-thanos-bucket"
        endpoint: "192.168.52.57:80"
        insecure: true
        access_key: "N2YYVI8PKLE3ZO5ODV22"
        secret_key: "udDUUjmFHa4ag03MPWdgmncwYmqYf6b1qMWIGbhJ"
        http_config:
          insecure_skip_verify: true
  # 
  # Quay specific configurations. Not needed if another vendor image registry is used.
  # 
  quay:
  #
  # The secret the config will be saved in
  #
    registry_name: lab
    config_secret: lab-quay-config-bundle
    #
    # config_yaml is set to the Quay configuration customising items like a user friendly server name.
    # This config also configures an external S3 storage to be used for image storage.
    #
    # ssl_cert and ssl_key are required to configure a site wide self-signed TLS certificates for the server.
    #
    config_yaml: |-
      ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
      #AUTHENTICATION_TYPE: Database
      AUTHENTICATION_TYPE: LDAP
      DEFAULT_TAG_EXPIRATION: 2w
      ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
      FEATURE_BUILD_SUPPORT: false
      FEATURE_DIRECT_LOGIN: true
      FEATURE_MAILING: false
      REGISTRY_TITLE: Red Hat Quay
      REGISTRY_TITLE_SHORT: Red Hat Quay
      FEATURE_PROXY_CACHE: true
      FEATURE_PROXY_STORAGE: true
      TAG_EXPIRATION_OPTIONS:
      - 2w
      TEAM_RESYNC_STALE_TIME: 30m
      TESTING: false
      SERVER_HOSTNAME: lab-registry.mgmt.tmetse.lab
      #DISTRIBUTED_STORAGE_CONFIG:
      #  default:
      #  - RadosGWStorage
      #  - access_key: NJBPAVFV8Y31FVJ1KZRL
      #    bucket_name: mgmt-cluster-bucket
      #    hostname: 192.168.52.57
      #    is_secure: false
      #    port: "80"
      #    secret_key: y6jP327JGRDdqBSc7UYhsZLzhZUAuBK9BPK2Ox1j
      #    storage_path: /datastorage/registry
      DISTRIBUTED_STORAGE_CONFIG:
        default:
          - RHOCSStorage
          - access_key: AWS_ACCESS_KEY_ID
            bucket_name: BUCKET_NAME
            hostname: BUCKET_HOST
            is_secure: true
            port: "BUCKET_PORT"
            secret_key: AWS_SECRET_ACCESS_KEY
            storage_path: /datastorage/registry
      DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
      DISTRIBUTED_STORAGE_PREFERENCE:
        - default      
      LDAP_ADMIN_DN: uid=ocp-binddn,cn=sysaccounts,cn=etc,dc=tmetse,dc=lab
      LDAP_ADMIN_PASSWD: LABldap2022
      LDAP_ALLOW_INSECURE_FALLBACK: false
      LDAP_BASE_DN:
      - dc=tmetse
      - dc=lab
      LDAP_EMAIL_ATTR: mail
      LDAP_UID_ATTR: uid
      LDAP_URI: ldaps://idm01.tmetse.lab
      LDAP_USER_FILTER: (&(memberOf=cn=giteauser,cn=groups,cn=accounts,dc=tmetse,dc=lab)(uid=%s))
      LDAP_USER_RDN:
      - cn=users
      - cn=accounts
      FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: true
      FEATURE_TEAM_SYNCING: true
      

    ssl_cert: |-
      -----BEGIN CERTIFICATE-----
      MIIEvzCCAyegAwIBAgIBDDANBgkqhkiG9w0BAQsFADA1MRMwEQYDVQQKDApUTUVU
      U0UuTEFCMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjIxMTMw
      MDQ1MDU0WhcNMjQxMTMwMDQ1MDU0WjA8MRMwEQYDVQQKDApUTUVUU0UuTEFCMSUw
      IwYDVQQDDBxsYWItcmVnaXN0cnkubWdtdC50bWV0c2UubGFiMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwQrGrptRG40IGjS1o47/NedtW9dmCMLUDO7K
      pEzUjUUE9nkXDG5NNJR0IU1x0cM8yiwdsTW9p0DWY23HOJyIJHlrnLbILHbeMtw5
      ZuGnKe8a1Z9X9oL0pccD43KY4cgcfntJqH3g/8vWJIc/d0EkRpDhnKbBDs8BjTjf
      Yojl1ChAsFP/PUsRUo2dl/dLTEJPN1QFENB87aMn+yWxHCN8fx7Y2USmFP03ccIo
      WTufED23mxmao1qVSB0/vx89e0hANFy1Q+xlF/KFt6pqUy93q1otn2FgnhXaVpKk
      HeqK9QFcMQ1c7RXGHqWuGVFchQ3AiRGEJsuv92HKgq7QStqbiwIDAQABo4IBUTCC
      AU0wHwYDVR0jBBgwFoAUYbstr2DbTPn75med5mXzUKSkggAwPAYIKwYBBQUHAQEE
      MDAuMCwGCCsGAQUFBzABhiBodHRwOi8vaXBhLWNhLnRtZXRzZS5sYWIvY2Evb2Nz
      cDAOBgNVHQ8BAf8EBAMCBPAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
      MHUGA1UdHwRuMGwwaqAyoDCGLmh0dHA6Ly9pcGEtY2EudG1ldHNlLmxhYi9pcGEv
      Y3JsL01hc3RlckNSTC5iaW6iNKQyMDAxDjAMBgNVBAoMBWlwYWNhMR4wHAYDVQQD
      DBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHQYDVR0OBBYEFEXn+2helBEUJOnOTHyW
      3f5g+zmEMCcGA1UdEQQgMB6CHGxhYi1yZWdpc3RyeS5tZ210LnRtZXRzZS5sYWIw
      DQYJKoZIhvcNAQELBQADggGBALB9EmB8cl0Z/5dXuBZ+zewUSaRpqt6kGXkMQpGB
      d8He8ij30k1MYisr6HoH1NOWO/8HD0QtODo0CNsV1OfcGsE7nPQD0V4mXpVreFUO
      2yxdNewByO19FVET6i8mVzT5jyOkiFEzq7Aurh511dV12M3jDU/wtlgzH24DdfAq
      PWpn0hH9ovbUQajIO11lMTylbi65+dHDUvN8a7E0yQMi7IKGU2t9qL3JlYeIEvQM
      hysYqyUw2RMOj6t86o9uBm4RrPG2zDj79qZtY2NyY9KalXmeTTLY8NvX6GClBuPp
      Sy/iOoz0QWTbQZYP2bhlZK59V64FbTiai4IqkJiRQgNTY1UXaEwKuCLNKAZH/zUl
      tiKvNy8pe7HFyrzQwRbBwklj2M9t5D8NJSu+OBMpnxz4G6lJetAa+w59+FkUqBmi
      bncqSSct+OsNvGz0qVf7JdVNNC1bYAdGZ9cn0xhcufrydLTS7K0XSwanKDfKGfiE
      N3WfmGYHXm+jkxmrASMbbGDd1Q==
      -----END CERTIFICATE-----

    ssl_key: |-
      -----BEGIN PRIVATE KEY-----
      MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDBCsaum1EbjQga
      NLWjjv81521b12YIwtQM7sqkTNSNRQT2eRcMbk00lHQhTXHRwzzKLB2xNb2nQNZj
      bcc4nIgkeWuctsgsdt4y3Dlm4acp7xrVn1f2gvSlxwPjcpjhyBx+e0mofeD/y9Yk
      hz93QSRGkOGcpsEOzwGNON9iiOXUKECwU/89SxFSjZ2X90tMQk83VAUQ0Hztoyf7
      JbEcI3x/HtjZRKYU/TdxwihZO58QPbebGZqjWpVIHT+/Hz17SEA0XLVD7GUX8oW3
      qmpTL3erWi2fYWCeFdpWkqQd6or1AVwxDVztFcYepa4ZUVyFDcCJEYQmy6/3YcqC
      rtBK2puLAgMBAAECggEBAIqpVeun7wuuMyq3v907YwByOvBkeYtDfxPHFtILygWr
      lRQCCNdKB7UECaK+QUqeRfUm2TEoXBFelmCXQynb7kLc4LqR5JljzNmVrLnEztFl
      Sc42hfWxPVAy8w0WjNBpcGY94rvfp5W18h0M9T6RESCLAzQF59jeQswRFQxvLz9D
      ZXo5ntaFmw8OBXtAwQGXAnoYTZxk2C/CRMzPBqUlPuaAW5sisZDnIUZxicvqT6l5
      pgDYaoSK27mQESfxZ3rZl3yFFUsbrSOhUt/uDMTM+3sKair7of2OoTfu5Yny2RXh
      qH+yJCxeovd4HTB0Hi8fm0dHv3Uf5uNSvccIpOMhulECgYEA92kbm+eJuacCyul3
      lULpdOh3W1FDcoCpDPxtSAvW8cvazGjomaSLRg2oqTxKhG7nzlbVNTAEl6PcwWQV
      y739NxqLqdckfx2F5u3xEQMss2/WrZx+yaCu8EbaknDMytN77BR444IZwZr9dcVh
      taJUEOEW7DVEKsE90bXhEuQymjkCgYEAx752LPxLq0W2fP3UPAqCwNGn2Bf486tV
      Ywn3pHw1WnXA83QVQxbWVHGFnFctnGgseFSQHssKPz6zj325Qx9U0oXt0DgNiwuq
      hQ8OHr6j2nJ2C4Ny9Lyb1uOQ8zOoraHDvvfR9sT8jd65PkTHRTL+R9I0sMTsgwYt
      n78UuslWs+MCgYEA2NbvUrogtG1S/kKXA2PstwETsx5LDe0DvRT0NqPh1HRFpMgB
      rL9RLanE++aSrPWDBw6FuSMHs1vznC+7BqHSb1w9sjKUkzBt7lL26GEu6WmI7wps
      +QxypraC1Lw2UUH/p47d0RBywIO1x2WiWI4YPd75tzaMMyjApK9Sv7rvOskCgYEA
      qIKU/iSmzcpVRyN4/mI7puH5AMRQoXlE4vXQtzKWbEd1Ta38FgpZLQpMlvWxJAd6
      pNVqdKAEeBC0uXRubCMtkyGr3IK9YjWoWPK3jdZ1M2BnGBWAUNoheuunKJXHUxxq
      oFxABThwfFuO2ep6VnXLsdmz3AF2Kp92tBMnMOGUxNMCgYA9tXfvHJDuaSJvag4H
      j39GEpmWAazf9kronlwfzmt5Vj2CQdQ3f6wDdfLY8K6b7EJIpm3fevhm23UfzUkq
      K9LYX9dSpHYe69pFtyQ/oUWgrNR9iNxpAXBoOFnJC2pyYWSHuBmnV4vTToWa6XTs
      BXZTwPo1LN+schqW9KmQZiBmIg==
      -----END PRIVATE KEY-----
  #
  # Define the standalone Assisted-Installer  attributes on this management cluster
  # Assumed it was installed by the Infrastructure Operator
  ai: 
    namespace: assisted-installer
    service_config_name: "assisted-service-config"
    #
    # Digest for AI controller image as detected at the time of mirroring
    # skopeo inspect docker://quay.io/edge-infrastructure/assisted-installer-controller:latest | egrep Digest | awk -F '"' '{print $4}'
    controller_image: "quay.io/edge-infrastructure/assisted-installer-controller@sha256:7de8be81d61ec1eece42cec358e9f18e25e4020be35451e6340866f487553575"
    
    #
    os_images:
      osp_version: '4.10'
      rhcos_version: 410.84.202202251620-0 
      root_fs_img_url: http://192.19.130.11:8989/openshift-v4/dependencies/rhcos/4.10/latest/rhcos-4.10.3-x86_64-live-rootfs.x86_64.img
      root_fs_iso_url: http://192.19.130.11:8989/openshift-v4/dependencies/rhcos/4.10/latest/rhcos-4.10.3-x86_64-live.x86_64.iso
  #
  ## to get rhcos_version boot root_fs_iso_url image and you'll see it on 1st line of console
  ## https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/latest/
  ## wget https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.8/48.84.202106301921-0/x86_64/rhcos-48.84.202106301921-0-openstack.x86_64.qcow2.gz?sha256=5a75df7b4d4dc1861093e520187a133eda3439019f280dc6e2f57edf70eb089d
  bmh: 
    prov_os_download_url: http://192.19.130.11:8989/rhcos-4.10.3-x86_64-openstack.x86_64.qcow2.gz?sha256=f581896eee37216021bfce9ddd5e1fd8289c366ca0d1db25221c77688de85fd7
    #prov_os_download_url: http://192.19.130.11:8989/rhcos-48.84.202106301921-0-openstack.x86_64.qcow2.gz?sha256=5a75df7b4d4dc1861093e520187a133eda3439019f280dc6e2f57edf70eb089d
    #prov_os_download_url: http://192.19.130.11:8989/rhcos-48.84.202106301921-0-openstack.x86_64.qcow2.gz?sha256=5a75df7b4d4dc1861093e520187a133eda3439019f280dc6e2f57edf70eb089d
  #
  # Some tuning for LSO volume set on this management cluster
  lso:
    maxdevice: 10
    minsize: 1Gi
#
# Site wide Openshift GitOps configuration options
#
  gitops:
    #hook_image: lab-registry.mgmt.tmetse.lab/gitops_mgmt/openshift4/ose-tools-rhel8:latest
    hook_image: registry.redhat.io/openshift4/ose-tools-rhel8:latest
    #hook_image: registry.redhat.io/openshift4/ose-tools-rhel8@sha256:3a430c4571983d4e774a7c2a6575086ad758d6a76724cc264ba80766abf5ee6b
    #hook_image: lab-registry.mgmt.tmetse.lab/gitops_mgmt/ose-tools-rhel8@sha256:c2230682e3f3a492967e7b62171cf363cff24fcb8252b2a0ca50e26dbbeb1b24
